language: python

matrix:
  include:
    - python: 3.6
      dist: xenial
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
    - python: 3.7
      dist: xenial
      env: TOXENV=coverage
    - python: 3.7
      dist: xenial
      env: TOXENV=lint
    - python: 3.8
      dist: xenial
      env: TOXENV=py38

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    - feffe.westermark@gmail.com
